#!/usr/bin/env python3
"""Build the Russian edition into ./ru/ (open ru/comic1.htm in a browser).

    python tools/build.py            # fuzzy (draft) translations included
    python tools/build.py --strict   # only reviewed (non-fuzzy) translations

Untranslated strings stay in English. Assets are copied from kidradd/, then
translation/overlay/ is copied on top (font, ru.js, ru.css, and later any
Russian replacements for GIFs with baked-in text).
"""
import argparse
import html
import json
import os
import re
import shutil
import sys

import polib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import krlib as K

SKIP_ASSETS = {'zip.sh', 'grabbag.psp', 'joulesattack.zip', 'WS_FTP.LOG'}


def load_translations(strict):
    pages, ui = {}, {}
    for f in sorted(os.listdir(K.PO_DIR)):
        if not f.endswith('.po'):
            continue
        for e in polib.pofile(os.path.join(K.PO_DIR, f)):
            if e.obsolete or not e.msgstr or (strict and 'fuzzy' in e.flags):
                continue
            if f == 'ui.po':
                ui[e.msgid] = e.msgstr
            else:
                pages[(e.msgctxt, e.msgid)] = e.msgstr
    return pages, ui


# ------------------------------------------------------------------ notes

NOTE_HEAD = re.compile(r'^##\s+(comic\d+a?)\s*[#\s]\s*([A-Za-z0-9_]+)\s*$')


def md_inline(s):
    s = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', s)
    s = re.sub(r'(?<![*\w])\*(?!\s)(.+?)(?<!\s)\*(?![*\w])', r'<i>\1</i>', s)
    s = re.sub(r'\[([^\]]+)\]\((https?://[^)\s]+)\)', r'<a href="\2" target="_blank" rel="noopener">\1</a>', s)
    return s


def load_notes():
    """{page: {panel: html}} from translation/notes/*.md.

    A note starts with a heading "## comic12#p3" (or "## comic12 p3") and runs
    until the next heading. Blank lines separate paragraphs. **bold**,
    *italic*, [link](https://...) and raw inline HTML are allowed.
    """
    notes = {}
    if not os.path.isdir(K.NOTES_DIR):
        return notes
    for f in sorted(os.listdir(K.NOTES_DIR)):
        if not f.endswith('.md'):
            continue
        key, buf = None, []

        def flush():
            if key:
                text = '\n'.join(buf).strip()
                if text:
                    paras = [re.sub(r'\s*\n\s*', ' ', p) for p in re.split(r'\n\s*\n', text)]
                    notes.setdefault(key[0], {})[key[1]] = ''.join(
                        p if p.startswith('<') else f'<p>{md_inline(p)}</p>' for p in paras)

        with open(os.path.join(K.NOTES_DIR, f), encoding='utf-8') as fh:
            for line in fh:
                line = line.rstrip('\n')
                m = NOTE_HEAD.match(line)
                if m or line.startswith('#'):
                    flush()
                    key, buf = ((m.group(1), m.group(2)) if m else None), []
                elif key:
                    buf.append(line)
        flush()
    return notes


# ----------------------------------------------------------------- assets

def copy_if_newer(src, dst):
    try:
        s, d = os.stat(src), os.stat(dst)
        if s.st_size == d.st_size and int(s.st_mtime) <= int(d.st_mtime):
            return False
    except FileNotFoundError:
        pass
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)
    return True


def copy_assets(comic_names):
    n = 0
    for root, dirs, files in os.walk(K.SRC):
        rel = os.path.relpath(root, K.SRC)
        for f in files:
            if rel == '.' and (f in SKIP_ASSETS or f[:-4] in comic_names):
                continue
            n += copy_if_newer(os.path.join(root, f), os.path.join(K.OUT, rel, f))
    for root, dirs, files in os.walk(K.OVERLAY):
        rel = os.path.relpath(root, K.OVERLAY)
        for f in files:
            n += copy_if_newer(os.path.join(root, f), os.path.join(K.OUT, rel, f))
    return n


def write_anim_table():
    table = {}
    for d in (K.SRC, K.OVERLAY):
        for f in os.listdir(d):
            if f.lower().endswith('.gif'):
                ms = K.play_once_ms(os.path.join(d, f))
                if ms:
                    table[f] = ms
                elif f in table:
                    del table[f]  # overlay GIF replaced a play-once one
    with open(os.path.join(K.OUT, 'kr-anim.js'), 'w', encoding='utf-8') as fh:
        fh.write('// Generated by tools/build.py: ms until the last frame of play-once GIFs.\n')
        fh.write('window.KR_ANIM = ' + json.dumps(table, sort_keys=True, indent=0) + ';\n')
    return table


# ------------------------------------------------------------------ pages

def js_string(obj):
    # Safe inside <script>: escape "</" so note HTML can't close the tag.
    return json.dumps(obj, ensure_ascii=False).replace('</', '<\\/')


def build_page(page, pages_tr, ui_tr, notes, ui_js):
    s = K.read_src(page + '.htm')
    reps = []
    stats = [0, 0]
    for u in K.segment(s, page):
        if K.is_ui(u):
            new = ui_tr.get(u.msgid)
        else:
            stats[1] += 1
            new = pages_tr.get((u.ctxt, u.msgid))
            if new:
                stats[0] += 1
        if new:
            reps.append((u.start, u.end, new))
    for a, b, new in sorted(reps, reverse=True):
        s = s[:a] + new + s[b:]

    s = re.sub(r'<html\b[^>]*>', '<html lang="ru">', s, count=1, flags=re.I)
    s = re.sub(r'<head>', '<head><meta charset="utf-8">', s, count=1, flags=re.I)
    inject = ('<link rel="stylesheet" type="text/css" href="ru.css">'
              '<script type="text/javascript" src="kr-anim.js"></script>'
              f'<script type="text/javascript">window.KR_UI = {ui_js}; '
              f'window.KR_NOTES = {js_string(notes.get(page, {}))};</script>'
              '<script type="text/javascript" src="ru.js"></script>\n')
    s = re.sub(r'</head>', lambda m: inject + m.group(), s, count=1, flags=re.I)
    with open(os.path.join(K.OUT, page + '.htm'), 'w', encoding='utf-8', newline='') as fh:
        fh.write(s)
    return stats


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--strict', action='store_true', help='skip fuzzy (unreviewed) translations')
    args = ap.parse_args()

    pages = K.comic_pages()
    os.makedirs(K.OUT, exist_ok=True)
    copied = copy_assets(set(pages))
    anim = write_anim_table()
    pages_tr, ui_tr = load_translations(args.strict)
    notes = load_notes()
    unknown = [p for p in notes if p not in pages]
    ui_js = js_string({'notes': ui_tr.get('notes', 'notes'),
                       'heading': ui_tr.get('Translator notes', 'Translator notes'),
                       'close': ui_tr.get('close', 'close')})

    done = total = 0
    for page in pages:
        d, t = build_page(page, pages_tr, ui_tr, notes, ui_js)
        done += d
        total += t
    n_notes = sum(len(v) for v in notes.values())
    print(f'{len(pages)} pages -> {os.path.relpath(K.OUT, K.ROOT)}/  '
          f'({done}/{total} strings translated, {n_notes} notes, '
          f'{len(anim)} play-once GIFs, {copied} assets copied)')
    if unknown:
        print('warning: notes for unknown pages: ' + ', '.join(unknown))


if __name__ == '__main__':
    main()
